---
- name: Include version-specific variables for CentOS/RHEL.
  include_vars: "RedHat-java-{{ java__version }}.yml"
  when: ansible_distribution == 'CentOS' or
        ansible_distribution == 'Red Hat Enterprise Linux' or
        ansible_distribution == 'RedHat'

- name: purgue old oracle-java
  apt:
    name: oracle-java*
    state: absent
    purge: yes
  when: ansible_distribution == 'Ubuntu'

- name: Add openjdk11 repository and signing key for Ubuntu 16.04
  block:
    - name: Add openjdk11 repository for Ubuntu 16.04
      apt_repository:
        repo: deb http://ppa.launchpad.net/openjdk-r/ppa/ubuntu xenial main

    - name: Add apt signing key
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: DA1A4A13543B466853BAF164EB9B1D8886F44E2A

    - name: Update apt cache
      apt:
        update_cache: true
  when: ansible_distribution_version == '16.04' and
        java__version == 11

- name: Install Java packages
  package:
    name: '{{ item }}'
    state: 'present'
  with_flattened:
    - '{{ java__base_packages }}'
    - '{{ java__jdk_packages }}'
    - '{{ java__packages }}'
    - '{{ java__group_packages }}'
    - '{{ java__host_packages }}'
    - '{{ java__dependent_packages }}'

- name: Update Java alternatives
  command: 'update-java-alternatives -s {{ java__alternatives }}'
  when: java__alternatives|d()

- name: Enable TLSv1
  lineinfile:
    path: "{{ java__java_security_conf_path }}"
    regexp: "{{ java__security_conf_jdk_tls_disabled_algorithms_first_line_default  }}"
    line: "{{ java__security_conf_jdk_tls_disabled_algorithms_first_line_to_enable_TLSv1 }}"
    backup: "{{ java__security_conf_enable_backup }}"
  when : java__enable_TLSv1

- name: Create environment var file
  copy:
    dest: "/etc/profile.d/java.sh"
    content: |
      JAVA_HOME=$(dirname $(dirname $(readlink -f $(command -v java))))
      export JAVA_HOME

- name: Make sure that Ansible local facts directory exists
  file:
    path: '/etc/ansible/facts.d'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: Save Java local facts
  template:
    src: 'etc/ansible/facts.d/java.fact.j2'
    dest: '/etc/ansible/facts.d/java.fact'
    owner: 'root'
    group: 'root'
    mode: '0755'
  register: java__register_facts

- name: Update Ansible facts if they were modified
  action: setup
  when: java__register_facts is changed
